apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      imagePullSecrets:          #docker hub 관련 정보 추가
      - name: dockerhub-secret #docker hub 관련 정보 추가
      containers:
      - name: my-webserver
        image: snowkwon/echo-hostname:630e4f6dbb823d1e59606e90d29fc7c6590e7c5a
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
