apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      imagePullSecrets:          #docker hub 관련 정보 추가
      - name: dockerhub-secret #docker hub 관련 정보 추가
      containers:
      - name: my-webserver
        image: snowkwon/echo-hostname:50094783d9fd15d566de11bc3f3fca31ca19ce3c
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
